### ISSUE TITLE
🐛 Invalid Sample Rate Detected

### ISSUE THREAD

**Issue by softwareantics** [KinsonDigital/CASL#143]
### Complete The Items Below

- [X] I have updated the title without removing the 🐛 emoji.
- [X] I searched whether or not an issue already exists for the bug I encountered.

### Current Behavior

The output pane is logging:

> Bitstream: INVALID SAMPLE RATE DETECTED

### Expected Behavior

It probably shouldn't do that 😂. 

### Steps To Reproduce

1. Create a new project
2. Reference the pre-release [here](https://www.nuget.org/packages/KinsonDigital.CASL/1.0.0-preview.11).
3. Setup your environment and create a new _Sound_.
4. For the sound file, [here](https://easyupload.io/rggcyi) is the file I used for testing.
5. Run your application, check the output pane in VS (or where ever your debugging information will show) to see the following results:

![image](https://user-images.githubusercontent.com/50978201/217249742-4c5e2e0e-d14b-4fef-960c-b527848c7f0b.png)

Please note that the sound file linked above will expire within 30 days - Apparently GitHub doesn't like MP3s 😢.

### Operating System(s)

- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] Mac OS
- [ ] iOS
- [ ] Other

### OS Version

**Operating System:** Windows 10 Home
**Hardware:** Intel i7-10710U @ 1.10GHz, 32GB RAM
**Toolchain:** VS Community 2022

### Anything Else

The sample rate of the sound file is 44.1kHz.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Attached the downloaded mp3 to this comment.
[title.zip](https://github.com/KinsonDigital/CASL/files/10680433/title.zip)

**Comment by CalvinWilkinson** [comment]
@softwareantics When were you getting the console output message?  When you were playing it? Loading it? Pausing?

**Comment by CalvinWilkinson** [comment]
@softwareantics dis-regaurd the previous comment.
After getting it running, I got the exact same thing that you did in the trace output.

After some quick investigation, it has to do with to being an MP3 file and the trace output message is coming from the [MP3 decoder library](https://github.com/Nihlus/MP3Sharp/tree/8731947ded938eaf3645a27feac4dbd1c63bc97e) that I am using to play MP3 files.

```cs
if (sync)
{
    sync = (((SupportClass.URShift(headerstring, 10)) & 3) != 3);
    if (!sync) Trace.WriteLine("INVALID SAMPLE RATE DETECTED", "Bitstream");
}
```
 which can be found [here](https://github.com/Nihlus/MP3Sharp/blob/8731947ded938eaf3645a27feac4dbd1c63bc97e/MP3Sharp/Decoding/Bitstream.cs#L312-L316)

I would not worry about it.  It plays fine for me.  It is just decoding some header information from the file header data and reporting some useful information.  As long as it doesn't crash and it sounds good, it will be fine.

**Comment by CalvinWilkinson** [comment]
> **Note** Closed without any changes
> **Reason:** Not an issue and works fine.
