### ISSUE TITLE
✨ Add the ability to load sounds from streams

### ISSUE THREAD

**Issue by softwareantics** [KinsonDigital/CASL#158]
### Complete The Items Below

- [X] I have updated the title without removing the ✨ emoji.
- [X] I searched whether or not a feature request already exists.

### Feature Request Purpose

I would like to allow the ability to load sounds from a `Stream` instead of a file path.

Need to create a `Music` class that will be streaming _**ogg**_ or _**mp3**_ sound. Usually, music is much larger so streaming provides the ability to be more performant.  This prevents having to load _**ALL**_ the sound data at once which causes the performance problem.

**Music Features:**
1. Looping
2. Pause
3. Play
4. Stop
5. Changing position in audio. (Fast forward & Rewind)
6. Play Speed
7. Volume control
8. Shows music state
9. Shows sound time length info
10. Ability to pick up where a streamed sound was playing when changing devices
> [!Note]
> This might be a bit of a challenge.  The `AudioDeviceManager` takes control over playing a sound and the state of the sound after connecting to a new device.  When switching devices, right before the device switch occurs, the state of the sound such as playing or paused, play speed, volume, etc are cached before the switch.  Once the device has been switched, the `Sound` class will reupload the data to the new device and then the `AudioDeviceManager` will handle setting the `Sound` back to its original state before switching to the new device.
11. Remove the `Sound.Stop()` method.
> [!Warning]
> This comes with https://github.com/KinsonDigital/CASL/labels/%F0%9F%A7%A8breaking%20changes.
> The reason for this is the ambiguity in regards to a higher level API when compared to _**OpenAL**_.  OpenAL does have the concept of `Stop` vs `Reset` vs `Pause`.  Though this fine level of control and state makes sense in the low-level world of OpenAL, it does not in the higher-level world of the CASL API.  This makes it confusing in regards to the difference between `Pause()`, `Stop()`, and `Reset()`.
12. Add the ability to detect when a device has been changed and switch to the next default device automatically.
    - An example of this would be with battery-powered headphones.  If you had playback to the headphones and the headphone battery died, we need to automatically witch to the new device that gets chosen by the OS.

### Solution

I'm not 100% sure about the solution here, but glancing over the code tells me this change might be relatively simple; at least for MP3s, I haven't taken a look at OOGs however.

[MP3Sharp](https://github.com/ZaneDubya/MP3Sharp/blob/dc9342152859d782df12a001bf719ce334c34b14/MP3Sharp/MP3Stream.cs#L57) can be provided a `Stream` within it's constructor. `Mp3AudioDataStream` is already set up in a way to handle this from the looks of it.

### Anything Else

This feature would be nice for me as my current [use](https://github.com/softwareantics/FinalEngine/blob/8f57d49e6cd36a60f00d970e5337e0e6e793ce2b/FinalEngine.Audio.OpenAL/OpenALSound.cs#L14-L17) of CASL is expecting a file path whereas every other place where I'm retrieving resources I use an abstraction of the current file system that returns a `Stream`.

In a nutshell, adding this feature will allow users to use CASL without being concerned about _how_ a file is retrieved.

> [!Note]
> Attached is a prototype of how to do streaming.
> [OpenALStreaming.zip](https://github.com/KinsonDigital/CASL/files/14219920/OpenALStreaming.zip)

### Acceptance Criteria
```[tasklist]
- [x] Music looping implemented
- [x] Music pausing implemented
- [x] Music play implemented
- [x] Music reset implemented
- [x] Changing position in music. (Fast forward & Rewind)  implemented
- [x] Play Speed
- [x] Volume control
- [x] Shows music state
- [x] Shows sound time length info
- [x] Swap out the mp3 test file for something else
- [x] Switching devices when not streaming audio works correctly
- [x] Switching devices when streaming audio works correctly
- [x] The `Sound.Stop()` method has been removed.
- [x] The `Sound` class renamed to `Audio`
- [x] The word "sound" replaced with the word "audio" where applicable in the "Sound/Audio" class and interface
- [x] Go through code base and `seal` all unsealed internal classes
- [x] Greatly simplify _**CASLTesting.Program.cs**_
- [x] Code coverage for the code base is acceptable
- [x] Solve issue with change device crashing with really short audio
```

### Issue Dependencies

- #337

### Related Issues
 - #290

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
I just noticed this in the backlog.  I thought about streams in the past but it was not a priority and currently isn't right now due to my current workload.  But it is something I am interested in.  I am not however familiar with it and would have to do some researching and prototyping for sure.

Once I know how to pull it off, then I can figure out how that currently fits into the current API and how it would affect the API.

Great suggestion!!

**Comment by CalvinWilkinson** [comment]
I have created the research issue below that could really help with streaming.  This issue will depend on the search results.
- #290

**Comment by CalvinWilkinson** [comment]
Hey, @softwareantics.  Just wanted to let you know that I have been researching this.  I have a prototype up and running. 
I do not know exactly when it will be done but I am planning for it to be out in the next upcoming release!!

**Comment by CalvinWilkinson** [comment]
It was decided not to implement SILK into CASL.  Checkout issue #337 for more information.

**Comment by mathew-odwyer** [comment]
I don't think this issue should have been closed. My issue wasn't centered around:

> Usually, music is much larger so streaming provides the ability to be more performant. This prevents having to load ALL the sound data at once which causes the performance problem.

As much as this is a nice-to-have feature my issue relates to the fact that I don't want to rely on CASL for loading the file from disk. I'd prefer to be able to load it by creating a stream:

```csharp
public static ISound LoadSound(string filePath)
{
    using (var stream = File.OpenRead(filePath))
    {
        return new Audio(stream, BufferType.Full);
    }
}
```

**Comment by CalvinWilkinson** [comment]
@mathew-odwyer 
Let me give you an update on what has change since this issue is quite old now.  

I am not sure if you know, but I added stream buffering and full audio buffering to CASL awhile back.  So basically, CASL does the streaming for you so you don't have to.  Just set the buffer type to `BufferType.Stream` and it just works.

```cs
Audio myAudio = new Audio("C:/my-audio/my-sound.ogg", BufferType.Stream);
```

Trust me when I say, implementing audio streaming was not trivial. If the built in CASL stream will suite your needs, I would recommend using that.  I also recommend having your sound effects that are short and frequently used (ex: weapons sounds) use `BufferType.Full` and the larger audio such as game music to use `BufferType.Stream`.
