### ISSUE TITLE
🚧Update ReadMe

### ISSUE THREAD

**Issue by dipanshurdev** [KinsonDigital/CASL#332]
### Complete The Items Below

- [X] I have updated the title without removing the ✨ emoji.
- [X] I searched whether or not a feature request already exists.

### Feature Request Purpose

- [x] Add Repo-rater badge (https://repo-rater.eddiehub.io/api/badge?owner=KinsonDigital&name=Velaptor)(https://repo-rater.eddiehub.io/rate?owner=KinsonDigital&name=Velaptor)

- [x] Add "h4 style="font-weight:bold;" align="left" >⭐ Don't forget to give us a star! ⭐</h4>"
 

_No response_

### Solution

- [x] Added Repo-rater badge link in README.md.
- [x] Added Star comment

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Closed without implementation:

Issues with broken badges as well as fear that the repo rater project will not continue.
It was decided to pull the badges.
